# Generated by Django 4.1.4 on 2022-12-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of your article.", max_length=100
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Set if article has to be published or not.",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        null=True,
                        help_text="Set this field the day when you published our article.",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Fill the content of our article."),
                ),
                (
                    "description",
                    models.TextField(
                        default="", help_text="Fill the description of article."
                    ),
                ),
            ],
        ),
    ]
